[package]
name = "minimap2-rs-test"
version = "0.1.0"
edition = "2021"


[[bin]]

name= "main"
path = "src/main.rs"


[dependencies]
minimap2 = "0.1.20+minimap2.2.28"
needletail = {version = "0.5"}
rayon = "1.5"
crossbeam-channel = "0.5"
num_cpus = "1.0"
